# Generated by Django 5.0.4 on 2024-06-10 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion_producto', models.CharField(max_length=255)),
                ('precio_producto', models.IntegerField()),
                ('stock_producto', models.IntegerField()),
                ('grado_alcoholico', models.FloatField()),
                ('litros', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('descuento', models.FloatField()),
                ('cod_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cerveceria.pedido')),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerveceria.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=155)),
                ('apellidos', models.CharField(max_length=255)),
                ('telefono', models.IntegerField(unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set_custom', related_query_name='user_custom', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set_custom', related_query_name='user_custom', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='correo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerveceria.usuario'),
        ),
    ]
