# Generated by Django 5.0.4 on 2024-06-14 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion_producto', models.CharField(max_length=255)),
                ('precio_producto', models.IntegerField()),
                ('stock_producto', models.IntegerField()),
                ('grado_alcoholico', models.FloatField()),
                ('litros', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombres', models.CharField(max_length=155)),
                ('apellidos', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('descuento', models.FloatField()),
                ('cod_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cerveceria.pedido')),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerveceria.producto')),
            ],
        ),
    ]
