# Generated by Django 4.0.6 on 2024-05-29 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod_pedido', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_pedido', models.DateField()),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerveceria.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('cod_pedido', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('precio_unitario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('descuento', models.FloatField()),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerveceria.producto')),
            ],
        ),
    ]
