# Generated by Django 5.0.6 on 2024-07-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GananciasProducto',
            fields=[
                ('cod_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'view_ventas_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField()),
            ],
            options={
                'db_table': 'historial_pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoPendiente',
            fields=[
                ('nombre_cliente', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('cod_pedido_id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_detalle_pedido', models.IntegerField()),
                ('cod_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fecha_pedido', models.DateField()),
            ],
            options={
                'db_table': 'view_pedidos_pendientes',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
